language: java
#sudo: required
dist: trusty
jdk:
- openjdk8
addons:
  ssh_known_hosts: github.com
before_install:
- git config --global user.email "build@travis-ci.org"
- git config --global user.name "Travis CI"
- git clone https://github.com/StarOceanMC/Maven -b repo
- chmod +x nebula
- chmod +x scripts/*
install:
- "./nebula up"
- "./nebula p"
script:
- mvn clean deploy install -N -DaltDeploymentRepository=internal.repo::default::file://$PWD/Maven
- mvn -pl Nebula-API clean javadoc:jar source:jar deploy install -DaltDeploymentRepository=internal.repo::default::file://$PWD/Maven
after_success:
- openssl aes-256-cbc -K $encrypted_99999ed70289_key -iv $encrypted_99999ed70289_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh -T git@github.com # Try connection
- 'export LATEST_COMMIT=`git log --pretty=format:"%s" HEAD -1`'
- cd Maven
- 'git remote set-url origin git@github.com:StarOceanMC/Maven'
- git add .
- 'git commit -m "[Nebula-API] $LATEST_COMMIT"'
- git push
cache:
  directories:
  - "$HOME/.m2/repository"
  - Paper/work/Minecraft
